//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmebaDevice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public string ConsumoEnergetico { get; set; }
        public string Seriale { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual Thing Thing { get; set; }
    }
}
