//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmebaDevice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<Floor> Floor { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Thing> Thing { get; set; }
        public virtual DbSet<ItemType> ItemType { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Listino> Listino { get; set; }
        public virtual DbSet<Prezzo> Prezzo { get; set; }
    }
}
