//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmebaDevice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prezzo
    {
        public int PrezzoID { get; set; }
        public double Price { get; set; }
    
        public virtual ItemType ItemType { get; set; }
        public virtual Listino Listino { get; set; }
    }
}
